clc
clear all

for i=1:80
    url='D:\Kuliah\Tugas Akhir\Skripsi\Data Bentuk\';
    a=int2str(i);
    b='\';
    c=horzcat(url,a,b);
    d='.png';
    movefile(horzcat(c,'Gbr A2-1',d),horzcat(c,'Gbr A1-3',d))
    movefile(horzcat(c,'Gbr A3-1',d),horzcat(c,'Gbr A1-4',d))
    movefile(horzcat(c,'Gbr C4-1',d),horzcat(c,'Gbr A1-5',d))
    movefile(horzcat(c,'Gbr A4-1',d),horzcat(c,'Gbr A2-1',d))
    movefile(horzcat(c,'Gbr A4-2',d),horzcat(c,'Gbr A2-2',d))
    movefile(horzcat(c,'Gbr A5-1',d),horzcat(c,'Gbr A2-3',d))
    movefile(horzcat(c,'Gbr A5-2',d),horzcat(c,'Gbr A2-4',d))
    movefile(horzcat(c,'Gbr A6-1',d),horzcat(c,'Gbr A2-5',d))
    movefile(horzcat(c,'Gbr A7-1',d),horzcat(c,'Gbr A3-1',d))
    movefile(horzcat(c,'Gbr A7-2',d),horzcat(c,'Gbr A3-2',d))
    movefile(horzcat(c,'Gbr A8-1',d),horzcat(c,'Gbr A3-3',d))
    movefile(horzcat(c,'Gbr A9-1',d),horzcat(c,'Gbr A3-4',d))
    movefile(horzcat(c,'Gbr B0-1',d),horzcat(c,'Gbr A3-5',d))
    movefile(horzcat(c,'Gbr B1-1',d),horzcat(c,'Gbr A4-1',d))
    movefile(horzcat(c,'Gbr B1-2',d),horzcat(c,'Gbr A4-2',d))
    movefile(horzcat(c,'Gbr B1-3',d),horzcat(c,'Gbr A4-3',d))
    movefile(horzcat(c,'Gbr B2-1',d),horzcat(c,'Gbr A4-4',d))
    movefile(horzcat(c,'Gbr B2-2',d),horzcat(c,'Gbr A4-5',d))
    movefile(horzcat(c,'Gbr B3-1',d),horzcat(c,'Gbr B0-1',d))
    movefile(horzcat(c,'Gbr B3-2',d),horzcat(c,'Gbr B0-2',d))
    movefile(horzcat(c,'Gbr B3-3',d),horzcat(c,'Gbr B0-3',d))
    movefile(horzcat(c,'Gbr B4-1',d),horzcat(c,'Gbr B0-4',d))
    movefile(horzcat(c,'Gbr B4-2',d),horzcat(c,'Gbr B0-5',d))
    movefile(horzcat(c,'Gbr B5-1',d),horzcat(c,'Gbr B1-1',d))
    movefile(horzcat(c,'Gbr B5-2',d),horzcat(c,'Gbr B1-2',d))
    movefile(horzcat(c,'Gbr B5-3',d),horzcat(c,'Gbr B1-3',d))
    movefile(horzcat(c,'Gbr B6-1',d),horzcat(c,'Gbr B1-4',d))
    movefile(horzcat(c,'Gbr B6-2',d),horzcat(c,'Gbr B1-5',d))
    movefile(horzcat(c,'Gbr B7-1',d),horzcat(c,'Gbr B2-1',d))
    movefile(horzcat(c,'Gbr B7-2',d),horzcat(c,'Gbr B2-2',d))
    movefile(horzcat(c,'Gbr B7-3',d),horzcat(c,'Gbr B2-3',d))
    movefile(horzcat(c,'Gbr B8-1',d),horzcat(c,'Gbr B2-4',d))
    movefile(horzcat(c,'Gbr B8-2',d),horzcat(c,'Gbr B2-5',d))
    movefile(horzcat(c,'Gbr B9-1',d),horzcat(c,'Gbr B3-1',d))
    movefile(horzcat(c,'Gbr B9-2',d),horzcat(c,'Gbr B3-2',d))
    movefile(horzcat(c,'Gbr C0-1',d),horzcat(c,'Gbr B3-3',d))
    movefile(horzcat(c,'Gbr C0-2',d),horzcat(c,'Gbr B3-4',d))
    movefile(horzcat(c,'Gbr C5-1',d),horzcat(c,'Gbr B3-5',d))
    movefile(horzcat(c,'Gbr C1-1',d),horzcat(c,'Gbr B4-1',d))
    movefile(horzcat(c,'Gbr C1-2',d),horzcat(c,'Gbr B4-2',d))
    movefile(horzcat(c,'Gbr C1-3',d),horzcat(c,'Gbr B4-3',d))
    movefile(horzcat(c,'Gbr C2-1',d),horzcat(c,'Gbr B4-4',d))
    movefile(horzcat(c,'Gbr C2-2',d),horzcat(c,'Gbr B4-5',d))
    movefile(horzcat(c,'Gbr C3-1',d),horzcat(c,'Gbr C0-1',d))
    movefile(horzcat(c,'Gbr C3-2',d),horzcat(c,'Gbr C0-2',d))
    movefile(horzcat(c,'Gbr C3-3',d),horzcat(c,'Gbr C0-3',d))
    movefile(horzcat(c,'Gbr C3-4',d),horzcat(c,'Gbr C0-4',d))
    movefile(horzcat(c,'Gbr C3-5',d),horzcat(c,'Gbr C0-5',d))
    movefile(horzcat(c,'Gbr C6-1',d),horzcat(c,'Gbr C1-1',d))
    movefile(horzcat(c,'Gbr C6-2',d),horzcat(c,'Gbr C1-2',d))
    movefile(horzcat(c,'Gbr C6-3',d),horzcat(c,'Gbr C1-3',d))
    movefile(horzcat(c,'Gbr C6-4',d),horzcat(c,'Gbr C1-4',d))
    movefile(horzcat(c,'Gbr C6-5',d),horzcat(c,'Gbr C1-5',d))
    movefile(horzcat(c,'Gbr C7-1',d),horzcat(c,'Gbr C2-1',d))
    movefile(horzcat(c,'Gbr C7-2',d),horzcat(c,'Gbr C2-2',d))
    movefile(horzcat(c,'Gbr C7-3',d),horzcat(c,'Gbr C2-3',d))
    movefile(horzcat(c,'Gbr C7-4',d),horzcat(c,'Gbr C2-4',d))
    movefile(horzcat(c,'Gbr C7-5',d),horzcat(c,'Gbr C2-5',d))
    movefile(horzcat(c,'Gbr C8-1',d),horzcat(c,'Gbr C3-1',d))
    movefile(horzcat(c,'Gbr C8-2',d),horzcat(c,'Gbr C3-2',d))
    movefile(horzcat(c,'Gbr C8-3',d),horzcat(c,'Gbr C3-3',d))
    movefile(horzcat(c,'Gbr C8-4',d),horzcat(c,'Gbr C3-4',d))
    movefile(horzcat(c,'Gbr C8-5',d),horzcat(c,'Gbr C3-5',d))
    movefile(horzcat(c,'Gbr C9-1',d),horzcat(c,'Gbr C4-1',d))
    movefile(horzcat(c,'Gbr C9-2',d),horzcat(c,'Gbr C4-2',d))
    movefile(horzcat(c,'Gbr C9-3',d),horzcat(c,'Gbr C4-3',d))
    movefile(horzcat(c,'Gbr C9-4',d),horzcat(c,'Gbr C4-4',d))
    movefile(horzcat(c,'Gbr C9-5',d),horzcat(c,'Gbr C4-5',d))
end